### ISSUE TITLE
Display settings crashes with some multi-display setups [$50]

### ISSUE THREAD

**Issue by pbirkbeck** [elementary/switchboard-plug-display#104] opened 2018-07-04 00:03 UTC
Display settings in switchboard do not open on elementary os juno

**Comment by danrabbit** [comment] 2018-07-04 00:10
Thanks for the report! Can you provide some more information? What kind of display set up are you running? Internal on a laptop? External on a desktop? Multiple displays? Anything noteworthy like HiDPI on some, but not all displays? What happens when you try to open Display settings? Does it freeze or does the window just close? Do you get an error messaging?

**Comment by pbirkbeck** [comment] 2018-07-04 00:15
I have a Dell XPS 13 9360 connected to Dell USB C dock with 2 external monitors with laptop lid closed. When I press displays in switchboard nothing happens and switchboard closes out. No error messages

**Comment by pbirkbeck** [comment] 2018-07-04 00:29
Also I get this in syslog when pressing displays -
Jul  3 17:28:42 paulb-xps13 io.elementary.cerbere.desktop[1435]: **
Jul  3 17:28:42 paulb-xps13 io.elementary.cerbere.desktop[1435]: ERROR:linkedlist.c:1175:gee_linked_list_real_get: assertion failed: (index < this._size)

**Comment by BZHDeveloper** [comment] 2018-07-04 12:03
Same thing here.

https://github.com/elementary/switchboard-plug-display/blob/master/src/Objects/VirtualMonitor.vala#L105
https://github.com/elementary/switchboard-plug-display/blob/master/src/Utils.vala#L38

unrecognized second screen, or the default config remove all modes :/

**Comment by btd1337** [comment] 2018-07-18 07:21
It confirmed. This error occurs just when we use an external monitor.

**Comment by btd1337** [comment] 2018-08-05 00:15
@danrabbit @codygarver @cassidyjames Any progress? This bug is critical!

**Comment by cassidyjames** [comment] 2018-08-06 15:32
@btd1337 there is not need to ping people not already on this issue; it's been confirmed, triaged, marked as high priority, and assigned to the beta2 milestone. If there is further work on it, that will show up on this issue (and notify anyone who has notifications on for the issue).

**Comment by cassidyjames** [comment] 2018-09-11 00:07
@danrabbit and I both experienced this with a specific display this weekend. We are both on HiDPI, and were connecting to a projector that had an HDMI extender. But I've also connected to a different display just fine and it doesn't crash. So I'm not sure what's causing it exactly, or how exactly to reproduce it.

**Comment by naaando** [comment] 2018-09-12 05:59
It's crashing because there's no boundary checking on VirtualMonitor.monitors, MonitorManager's get_monitor_config() have a foreach loop around line 178 that might append virtual monitors without monitors, I didn't find a solution atm tho.
This should be production ready code? There's a huge chunk of code inside a single function and there's no reason to VirtualMonitor hold a monitors array since MonitorManager have a array of VirtualMonitors too.
BTW was a huge experience to track this bug with gdb, learned a lot.

**Comment by davidmhewitt** [comment] 2018-09-13 16:34
I'm unable to reproduce this on my HiDPI laptop with 2 external monitors (both with and without the lid closed) and all the combinations of different monitors attached to different ports.

I'd be willing to do some remote access debugging if someone has a machine that can consistently reproduce the fault and is willing to let me remote in. Something a bit like pair programming I guess, as I'd probably look to test out a few code changes on the same machine.

**Comment by cassidyjames** [comment] 2018-09-13 17:59
@davidmhewitt I think @Philip-Scott was saying it was pretty reproducible for him at home. Unfortunately the situation with me and @danrabbit was at a conference venue, so we don't have access to that hardware anymore. I'll see if I can get it to consistently reproduce here with an old monitor or something, though, and let you know.

**Comment by naaando** [comment] 2018-09-13 19:07
Guys more update on tracking the issue, apparently the serial isn't being attributed for some devices, I've made a hash joining connector+vendor+product+serial. IDK if this hash could change but I guess it's safe to use, sending PR #120

**Comment by Philip-Scott** [comment] 2018-09-16 18:06
Fixed in #121 :)

**Closed by Philip-Scott** 2018-09-16 18:06 UTC
Labels: Bounty, Priority: High, Status: Confirmed
