### ISSUE TITLE
(Privacy)Question: Does the night light setting "sunset to sunrise" require an Internet connection?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/switchboard-plug-display#239] opened 2020-04-26 17:52 UTC
Since sunset and sunrise vary daily, I just assume that an internet connection is required for this setting to work. If so, where exactly does this setting get its data from?
Maybe there should be a hint for the users to explain this?

**Comment by 4jNsY6fCVqZv** [comment] 2020-07-02 14:12
@cassidyjames Do you see this as a privacy issue?

**Comment by davidmhewitt** [comment] 2020-08-11 12:49
`gsd-color` is the component that handles this (from the GNOME project). It uses your latitude and longitude to calculate (using good old fashioned trigonometry, based on the rotation of planetary bodies etc) sunrise and sunset times:

https://github.com/GNOME/gnome-settings-daemon/blob/d6bb63fd88e2c92d96ea6bc7a4e43c6756edb460/plugins/color/gsd-night-light-common.c#L50

The location is obtained from GeoClue, which usually uses MLS (https://location.services.mozilla.com/) unless you've disabled it with the location services switch in the settings, or unless you happen to have a supported GPS receiver on your device.

I guess if it can't get a location, this feature just doesn't work.

**Comment by davidmhewitt** [comment] 2020-08-14 09:30
Given that this was a question, not a bug report, I'll close this as I feel I have adequately answered the question for now.

Please feel free to follow up if necessary.

**Closed by davidmhewitt** 2020-08-14 09:30 UTC
