### ISSUE TITLE
Monitor identification overlays are listed as app windows

### ISSUE THREAD

**Issue by jlnr** [elementary/switchboard-plug-display#111] opened 2018-08-07 22:24 UTC
A small cosmetic issue:

![screenshot von 2018-08-08 00 22 02](https://user-images.githubusercontent.com/70772/43805771-5ca8a4bc-9aa1-11e8-8144-fb0aa60e655e.png)

While in the Displays plug, there are two bullets below the Switchboard dock icon, and three entries are listed in the right-click window menu. I assume that these are the colored overlay windows, like the blue one in the top left corner of the screenshot.

**Comment by lenemter** [comment] 2024-01-08 07:10
Duplicate of https://github.com/elementary/switchboard-plug-display/issues/1

**Closed by lenemter** 2024-01-08 07:10 UTC
Labels: Priority: Low, Status: Confirmed
