### ISSUE TITLE
Can't disable internal monitor (Laptop)

### ISSUE THREAD

**Issue by D18x** [elementary/switchboard-plug-display#222] opened 2020-01-18 14:06 UTC
I've tried to disable my 11" notebook internal display, but i can't get it done...
![Screenshot from 2020-01-18 14-05-58](https://user-images.githubusercontent.com/33224307/72664969-b08fa580-39fb-11ea-95cf-5e6ed41b338d.png)
![Screenshot from 2020-01-18 14-05-58](https://user-images.githubusercontent.com/33224307/72664977-c2714880-39fb-11ea-9341-0eef634dcbe3.png)

**Comment by jeremypw** [comment] 2020-01-18 18:12
Did you try setting the external monitor as the primary monitor first?

**Comment by MarlonMrN** [comment] 2020-04-02 03:01
it's really broken. see https://github.com/elementary/switchboard-plug-display/issues/131

host + R     does the job of changing how you use the displays, just keep hitting it until you reach the desired state

**Comment by davidmhewitt** [comment] 2020-08-10 12:09
Duplicate of #131

**Closed by davidmhewitt** 2020-08-10 12:09 UTC
Labels: Status: Duplicate
