### ISSUE TITLE
Rotation lock

### ISSUE THREAD

**Issue by someuseragain** [elementary/switchboard-plug-display#133] opened 2018-10-17 14:27 UTC
My laptop has an auto rate sensor, it doesn't work in linux as it should, so I usually lock screen rotation in gnome drop-down menu in pop-os or ubuntu, but I had to use dconfig editor to force the screen into normal orientation, this isn't friendly to newcomers and I have no idea how to lock rotation in the login screen which is sometimes upside down or sideways, also in the login screen can you make it so that I don't have to click on the password field but it is active by default and I can just type right away. Thank you for your attention.

**Comment by davidmhewitt** [comment] 2018-10-17 14:32
Hey,

Thanks for the bug report. The display settings already technically have a setting to turn on rotation lock. However, the setting only appears if the laptop has a touchscreen. This is due to there being no consistent way to detect an accelerometer when the feature was implemented, so it was assumed that laptops with touchscreens might also do auto rotate.

There's an open bug report about this here: https://github.com/elementary/switchboard-plug-display/issues/116

Is it possible the setting hasn't appeared because you don't have a touchscreen? Or maybe your touchscreen hasn't been detected properly.

**Comment by peteruithoven** [comment] 2018-10-17 14:33
(The password not getting focus is a known issue: https://github.com/elementary/greeter/issues/144 )

**Comment by cassidyjames** [comment] 2018-10-24 23:06
@someuseragain does your device have a touch screen? If not, then this is a duplicate of #116 so I'm closing this for now. If that's not the case, feel free to comment/reopen.

**Closed by cassidyjames** 2018-10-24 23:06 UTC
Labels: Status: Incomplete

**Comment by peteruithoven** [comment] 2019-02-09 15:45
I think the issue might have been that the rotation lock doesn't apply to the greeter? There is an open issue in the Greeter repo that I hope to move to this repo: https://github.com/elementary/greeter/issues/216
