### ISSUE TITLE
Hardware-Displays-ScalingFactor with External HDMI display Bug

### ISSUE THREAD

**Issue by chamleongates** [elementary/switchboard-plug-display#287] opened 2021-02-20 18:41 UTC
I have discovered a couple of bugs related to using an external monitor via HDMI on a laptop.  But while I have you this OS is amazing!  You guys are all doing GREAT work!

**The Hardware:**
Lenovo Thinkpad Yoga X1 with:   1920x1080@60Hz LED screen)
LG 22" (with a 1920x1080@60Hz LED screen) & HDMI connection

**The Software:**
elementary OS 5.1.7 Hera
Linux 5.4.0-65-generic
GTK 3.22.30

**Bug/Issue #1**
If you only use an external monitor connected via HDMI (& do not intend to the laptop screen), it is not possible to login to elementary OS.  This is because the login screen only displays on the laptop.  (The display should be mirrored so you can login using the external monitor.)

**Bug/Issue #2**
When using an externally connected HDMI monitor (with the exact same resolution as the laptop screen), there is a problem with mirrored mode.  Select All-Settings/Displays.  At the bottom of the Displays window, you can toggle the Mirror Display on.  Doing so does mirror the laptop and external display.  HOWEVER, the scaling factor is incorrectly changed from LoDPI to Pixel Doubled.  In a normal scenario, one would expect to be able to toggle the Scaling factor back but the Display window size is larger than the monitor (or Laptop screen) can display.  As a result, you have to use tab, and spacebar and enter to GUESS at which settings are being changed (because they are off the screen.)  Making the Display window much smaller should resolve the issue.  :-)

**Comment by cassidyjames** [comment] 2021-08-12 18:01
Please check for existing reports, use the issue templates, and file reports separately; as-is this issue is two separate issues that don't provide the right kind of information, and both have already been reported. :sweat_smile:

First issue is a duplicate of #273; second is likely a duplicate of https://github.com/elementary/greeter/issues/65

**Closed by cassidyjames** 2021-08-12 18:01 UTC
