### ISSUE TITLE
request to add sub pixel layout and hinting settings

### ISSUE THREAD

**Issue by renderorange** [elementary/switchboard-plug-display#164] opened 2019-03-05 06:05 UTC
Although sub pixel layout and hinting settings are available through the dconf editor, it would be great to have them available through the display settings for quick access (and persistent through major updates).

The default settings most likely work for the most monitors and most users, but through HDMI at 60hz (4k UHD color enabled tv), text looks pretty bad.  It's fixable, but would be nice to have access to the settings by default.

Greyscale hinting seems to help as well, at least for me.

Thanks :)

**Comment by renderorange** [comment] 2019-03-05 23:12
EDIT: dconf, not gconf :)

**Comment by danirabbit** [comment] 2023-06-08 17:14
Closing as a duplicate of https://github.com/elementary/switchboard-plug-pantheon-shell/issues/288

**Closed by danirabbit** 2023-06-08 17:14 UTC
