### ISSUE TITLE
Make it work with latest Gala [$110]

### ISSUE THREAD

**Issue by tintou** [elementary/switchboard-plug-display#70] opened 2017-12-12 23:47 UTC
Get rid of libgnome-desktop-3.0, use libmutter DBus API

---
There is a bounty on this issue in [Bountysource](https://www.bountysource.com/issues/52640475-make-it-work-with-latest-gala)

**Comment by tintou** [comment] 2018-05-02 23:35
started here
https://github.com/elementary/switchboard-plug-display/tree/tintou/mutter-api
help always welcome

**Comment by danrabbit** [comment] 2018-05-27 21:56
Closing since the branch was merged. We can make new individual reports if there are regressions

**Closed by danrabbit** 2018-05-27 21:56 UTC
Labels: Bounty, Priority: High, Status: In Progress
