### ISSUE TITLE
Rotation lock is bound to touch, not accelerometer

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-display#126] opened 2018-10-02 05:40 UTC
Right now we show rotation lock for any touch screens. Instead, we should actually detect the accelerometer.

**Comment by danrabbit** [comment] 2018-10-02 15:09
Duplicate of #116 :)

**Closed by danrabbit** 2018-10-02 15:09 UTC

**Comment by cassidyjames** [comment] 2018-10-02 17:01
@danrabbit d'oh, I swear I searched for this issue first. I guess not.
