### ISSUE TITLE
Night Light does not work on all monitors

### ISSUE THREAD

**Issue by webmasterlv** [elementary/switchboard-plug-display#270] opened 2020-11-11 20:54 UTC
elementary OS 5.1.7 Hera
Linux 5.4.0-52-generic
GTK 3.22.30

Radeon RX 5700XT
3 monitors via DisplayPort

Night light works on 2 of 3 monitors. It doesnt matter how i rearrange displays.

**Comment by danirabbit** [comment] 2023-06-08 17:20
Closing as a duplicate of #212

**Closed by danirabbit** 2023-06-08 17:20 UTC
