### ISSUE TITLE
"Use this Display" switch doesn't work

### ISSUE THREAD

**Issue by jess-sch** [elementary/switchboard-plug-display#131] opened 2018-10-16 22:59 UTC
I just installed Juno and I noticed that disabling my ThinkPad X230's internal display doesn't work. It just stays on.

Steps to reproduce:
Boot into Juno install media or install it and then:
1. Connect an external monitor to your laptop
2. System Settings -> Display
3. Flip the "Use this Display" switch on your internal display
4. Apply the changes
5. See how nothing has changed at all

**Comment by marzochi** [comment] 2018-10-17 12:19
Same error for me. I can't disable internal screen on Juno. I can do it on Loki.

![image](https://user-images.githubusercontent.com/8195419/47085667-f883b380-d21f-11e8-82d2-cc83771b817a.png)

**Comment by deyvisonrocha** [comment] 2018-10-19 17:44
One way to work around this is to temporarily use Super + P to change until only the external monitor is left.

**Comment by wout** [comment] 2018-10-20 20:17
I can confirm the same issue on my Dell XPS 15 9560. There are some related problems due to this problem.

**No tray nor dock after sleep**

While using an external monitor, my laptop is closed. This works fine as long as the system does not go to sleep. Waking it up is a pain because it does not listen to the wireless mouse or keyboard (also Dell). Touching the built-in keyboard wakes up the system but then I have two screens missing the to menu bar/tray as well as the dock. The only thing I can do in this scenario is a hard reboot.

**Not dock nor tray after reboot**

This morning I logged in and again, no tray or dock were showing, so I did a reboot without the external monitor. But even after a reboot, they didn't show up. I had to manually launch the switchbaord (`/usr/bin/io.elementray.switchboard`) though the terminal to be able to access display settings, where I fiddled a bit with the settings. After rebooting the tray and dock were back again.

**Comment by nikitati** [comment] 2018-10-21 08:14
Confirmed on my ASUS zenbook UX360CA. The only option to disable laptop display is to cycle through monitor setups with super + P, as proposed above. But cycling sometimes breaks the ability to change wallpapers (sic!). Wallpaper change is then only applied after restarting the session. This is seriously messed up.

**Comment by kt1024** [comment] 2018-10-23 03:13
juno, tested w 3 notebooks:

- 1 x dell with intel i915 controller : display setting works as expected.
- 2 x thinkpad e330 (i915+nvidia gf610m). : unknown display can not be truly disabled, super+p key not work at all. thus, display setting is ok in bionic 18.04.

**Comment by kt1024** [comment] 2018-10-23 11:04
more test:
- fresh install, notebook with 1 intel video card. and a external 24' display(HDMI connected).
- setting->display->select 'Buld-in Display' -> un-select 'Use this display': nothing happened.
- use super+p combo, can make external hdmi display as single/only display.
- after reboot 2 screen/display are both activated. have to press super+p again to disable build-in display.(use external display only)

**Comment by msmaldi** [comment] 2018-10-23 22:46
Same problem, on acer E1-572
On Loki work perfect

**Comment by LanceGundersen** [comment] 2018-10-23 23:30
Confirmed on Dell XPS 13 9360 with eGPU. Juno 5 fresh install last night.

**Comment by kt1024** [comment] 2018-10-24 02:17
tried multiple times today,

- notebook w 1 intel gpu, set display to use only external display (use super+p).
- reboot
- password input box is not focused, screen goes to build-in display.  external display is in black, but mouse can move to (external display)
- after login, both screen was activated: external as primary, build-in as extend screen. 
- right after screens show up, press super+p has no responds.
- wait about 5 seconds or more, super + p finally can act, but can use mouse to start apps. (same hardware on Loki don't have to wait that time)

```
hw info:
model:  Dell Latitude E5250
cpu:    i5-5300U CPU @ 2.30GHz
mem:    12GB
disk:   256GB ADATA SP920SS SSD
auto start apps: albert luncher, synology cloudstation drive, fcitx input.
network: wired connected, wireless disabled.
```

**Comment by cassidyjames** [comment] 2018-10-24 23:07
Marking as high priority and confirmed since it's affecting a lot of people and we've gotten a lot of reports of this.

**Comment by cassidyjames** [comment] 2018-10-24 23:12
From #106:

>Not sure if it's related (or the same) to #38 and it's a regression from Loki
>
>Running Juno on an Optimus Enabled Laptop (with an GF106 GT630m). And i'm also on a "three monitor setup" (My broken laptop screen (which I disabled using the laptop Fn Key), my external monitor (probably isn't needed to give the model) on the VGA cable and the virtual nvidia screen.

>Also using the nvidia-driver-390 package from AppCenter, with the Intel profile (Nvidia card can't draw anything on the screen..)
>
>And the display settings (such as disabling the laptop screen and the nvidia virtual offscreen) doesn't do anything (not even blink the screens), worked fine on Loki.
>
>How can I grab some logs from switchboard?
–@h4ndshake

>I'm unable to disable monitors too
–@naaando

**Comment by rsolvang** [comment] 2018-10-29 14:11
I have the same problem on my x220 with an external monitor – the internal display won't turn off. I solved it temporary by installing ARandR which allows me to turn it off, but not persistently. After a reboot, the internal display is activated again.

**Comment by h4ndshake** [comment] 2018-10-29 14:55
@rsolvang You don't need ARandR, it's really simple to turn it off with the good ol' `xrandr`

Just type `xrandr --output <your display name> --off`

You don't even need to sudo this! But it's not persistent. (Will be reverted on reboot)

_Enviado do meu M5 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by matej-marcisovsky** [comment] 2019-02-20 10:48
First time digging into this but I noticed some unexpected things.

1. https://github.com/elementary/switchboard-plug-display/blob/93bb86f1d07b49f4cd5e7b54687d46452a8bb088/src/Objects/VirtualMonitor.vala#L56
It always return `true` so this can not work at all.

2. There is no turn off settings in `org.gnome.Mutter.DisplayConfig`. In TODO list there is note about that.
https://gitlab.gnome.org/GNOME/mutter/blob/7bd668e6d0081ff4a22617625347e54ca7138819/src/org.gnome.Mutter.DisplayConfig.xml
https://gitlab.gnome.org/GNOME/gnome-control-center/blob/3ccdd42b95963915593e10ece1b58e462c55bb35/panels/display/TODO#L706

3. Also noticed that `org.gnome.SettingsDaemon.XRANDR` plugin has been removed so maybe SettingsDaemon.vala is useless.
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/commit/cbf313e689f5853b85c6f7c08ac233688408c8e8
https://github.com/elementary/switchboard-plug-display/blob/93bb86f1d07b49f4cd5e7b54687d46452a8bb088/src/SettingsDaemon.vala

I suggest to completele remove the switch until `org.gnome.Mutter.DisplayConfig` supports this feature.

**Comment by wandertorres** [comment] 2019-02-22 10:42
O mesmo acontece aqui no meu Lenovo Ideapad 310. Além de não desativar os monitores através da funcionalidade Use this screen, por vezes a transparência do Wingpanel também não funciona com dois monitores, ficando apenas no modo Translucido.

Sou um entusiasta do Elementary OS e venho tento problemas com monitor externo desde o Loki.

**Comment by felix91gr** [comment] 2019-03-08 03:33
I'm experiencing this exact same problem. I'm gonna try @rafifos's suggestion, I hope it works as a temporary fix 🤞🏻

**Comment by felix91gr** [comment] 2019-07-04 16:02
What is the state on this? Tell me if it's possible to accelerate this through more bountiness.

**Comment by santropedro** [comment] 2019-08-09 23:29
Same exact issue, Lenovo Ideapad

**Comment by floi** [comment] 2019-08-12 13:46
Not sure if further +1's are still helpful, but I'm having the same issue with a fresh Juno install on a Dell Precision 5530.

Thanks for the workaround @deyvisonrocha !

**Comment by simgui8** [comment] 2019-08-13 11:52
Same problem on a fresh Juno install

**Comment by jean-lourenco** [comment] 2019-08-17 23:17
I'm having the same problem with Juno.
The issue is worse when I lock my laptop and close the lid. When I open it again (even if I have disabled the display before) the unknow display is shown as default somewhat, and I can just see a black screen. I have to cycle through the displays with super + p to find the right one to log in.

**Comment by Hedronmx** [comment] 2019-09-25 19:42
Still having this issue

**Comment by asimsalam** [comment] 2019-10-17 02:23
I too still see this issue with a Thinkpad T490 connected to two external monitors.
Moreover when I turned the monitor off using xrandr and locked the session, I did not get a unlock prompt. The only way out was to reboot the system from another tty.

**Comment by Hedronmx** [comment] 2019-12-05 04:41
Just released version 5.1 and this basic feature is still buggy.... incredible.

**Comment by felix91gr** [comment] 2019-12-05 05:27
It *is* a basic feature. But this system is free, and even though I don't like how they prioritize certain things, I do appreciate the work they take for it.

**Comment by Hedronmx** [comment] 2019-12-05 05:43
> It _is_ a basic feature. But this system is free, and even though I don't like how they prioritize certain things, I do appreciate the work they take for it.

Of course!! This is my favorite OS of all time... It is just baffling that such issue can last unresolved for so long. Even when the developers themselves tagged it as priority

**Comment by murermader** [comment] 2019-12-10 13:38
Just installed 5.1 Hero and am kinda amazed how this feature is still broken **after over a year**, without a real fix or viable workaround. Even a major version has been released during that period, and this bug is still not fixed.

**Comment by starrabb1t** [comment] 2020-02-27 06:41
Same problem on Hera 5.1.2

**Comment by MarlonMrN** [comment] 2020-04-02 02:58
Just installed 5.1.2 Hera on my dell e5440 and I'm facing the same problem.

**Comment by alfonsojon** [comment] 2020-04-07 00:07
I'd like to add that this issue doesn't just impact laptops; it also impacts desktops. I keep accidentally putting windows on my TV (third "monitor"). For now, I have it disconnected.

**Comment by MarlonMrN** [comment] 2020-04-07 00:43
> I'd like to add that this issue doesn't just impact laptops; it also impacts desktops. I keep accidentally putting windows on my TV (third "monitor"). For now, I have it disconnected.

Use Super+P as a workaround, so you can really disable it. Keep hitting it until you get your desired state

**Comment by tp6060** [comment] 2020-04-09 07:59
Same here. Worked well on loki - stopped working after upgrading to hera. Super+P works around.

**Comment by ErikMvk** [comment] 2020-04-29 02:49
Hey. Running latest version of elementary OS Hera and same problem here, i clicked on "use this display" and nothing happens. Super+P works but I have to use it everytime I plug my TV to watch a show. It's kinda annoying. Thanks!

**Comment by grmain** [comment] 2020-05-15 17:41
Hi, anything new?

**Comment by alfonsojon** [comment] 2020-05-16 05:11
I have installed Switchboard from the Unstable PPA and it seems to be fixed there.

**Comment by alfonsojon** [comment] 2020-06-26 01:51
For some reason my $15 bounty I provided for this bug report was refunded. Hmm...

**Comment by felix91gr** [comment] 2020-06-26 04:29
Yah, they're switching from BountySource to Github Sponsors

**Comment by cassidyjames** [comment] 2020-10-27 21:28
@alfonsojon Bountysource was being very unreliable and shady, see: https://blog.elementary.io/goodbye-bountysource-hello-github-sponsors/

We refunded all bounties and closed our Bountysource account.

**Comment by alfonsojon** [comment] 2020-10-28 12:56
Just read about that, that is very sketchy. Big thanks to everyone at Elementary for being proactive about this; I would have never otherwise seen that! I need to read the blog more often.

**Comment by LionsSharks15** [comment] 2020-12-22 15:06
This is still an issue on elementary OS 5.1.7 Hera. I had to use ARandR to disable my laptop display and only use my TV.

**Comment by PetrBlaha** [comment] 2021-06-02 09:08
Is there any update (will be in OS 6) regarding this issue? I am experiencing this on fresh install of OS 5 (thinkpad t480, monitor connected via usb-c dongle). It is not showstopper for me, but it would be much better experince if this would work :)

**Comment by jeremypw** [comment] 2021-06-02 15:12
The PR https://github.com/elementary/switchboard-plug-display/pull/228 provides at least a partial fix but is awaiting testing and review by a dev with a HiDPI monitor.  Until someone approves it, it cannot be merged.

**Comment by Hedronmx** [comment] 2021-08-14 01:37
Its incredible that a bug this important still unfixed. Eos 6 released with this same issue. 3 years have gone by....

**Comment by grmain** [comment] 2021-08-14 11:15
« This comment was marked as spam ». I am amazed. 3 years ignoring a major bug, 1 hour to mark a comment reminding it as spam. 
Congrats. I moved away from eOS since first beta of eOS 6, I was already happy doing so, I am happy having a computer that simply works, but now I am totally thrilled you guys and girls confirm this OS is pointless as an OS. After years it is still no more than an icon pack.

**Comment by Hedronmx** [comment] 2021-08-18 01:50
@grmain Just found out they marked my comment as spam... wow

**Comment by davidmhewitt** [comment] 2021-08-18 08:30
At this point, the issue is confirmed and well understood. There are a large number of comments and it can be difficult for us as developers to find the information we need in the thread as a result.

So, any comments that do not add anything useful to the discussion will be hidden to save time as we're reading the thread.

**Closed** 2021-08-18 20:41 UTC
Labels: Status: Confirmed, Priority: High, In progress
