### ISSUE TITLE
Scaling factor 3x after enabling display mirror mode 

### ISSUE THREAD

**Issue by davidak** [elementary/switchboard-plug-display#303] opened 2021-08-01 21:40 UTC
## What Happened

I enabled mirror mode. The resolution of the smaller display was used and scaling factor was set to 3x. I was not able to disable it again because the settings window was too big for the screen.

![signal-2021-08-01-222141](https://user-images.githubusercontent.com/91113/127785767-899f43a9-63a9-475f-9522-699ab9f452ca.jpeg)

(is there a command to reset the mirror mode? help)

## Expected Behavior
Scaling factor should not change when enabling mirror mode

## Steps to Reproduce

1. enable mirror mode
2. ???
3. caling factor 3x

### Logs
This seem to be the relevant part:

```
Aug 01 23:16:33 gaming .gsd-color-wrap[1889]: could not find device: property match 'XRANDR_name'='HDMI-A-1' does not exist
Aug 01 23:16:33 gaming .gsd-color-wrap[1889]: could not find device: property match 'XRANDR_name'='HDMI-A-1' does not exist
Aug 01 23:16:33 gaming .gsd-color-wrap[1889]: could not find device: property match 'XRANDR_name'='HDMI-A-1' does not exist
Aug 01 23:16:33 gaming .gsd-color-wrap[1889]: could not find device: property match 'XRANDR_name'='HDMI-A-1' does not exist
```

I get these lines after plugging the second display in and after unplugging it.

Here is the full log: https://gist.github.com/davidak/abd3ef7126fece6d9bfc9cc3c356b438

Chromium crashed when i unplugged the second display and the resolution changed, so i'm writing this issue the second time.

## Platform Information

NixOS 21.11.git.f858f91350c (Porcupine) (build from WIP PR https://github.com/NixOS/nixpkgs/pull/130380)
pantheon.switchboard-plug-display 2.3.0

The second display is connected with a HDMI-to-VGA converter. It is 16:10 and can display 1440x900.

**Comment by jeremypw** [comment] 2021-08-02 08:33
Looks like a problem determining a suitable resolution when monitors differ in resolution and aspect ratio.  Not sure how mirroring is supposed to work under these circumstances.  However, we should make sure there is enough resolution to display the plug!

**Comment by cassidyjames** [comment] 2021-08-02 15:59
@davidak to help resolve it/restore settings, you can hold the Super key down and then click and drag the window around to get to the parts off-screen. That should let you set the scaling factor at the bottom-left to 1× if that's what's causing the issue.

**Comment by davidak** [comment] 2021-08-02 18:13
@cassidyjames thanks! the scaling was actually 3x, so that's the issue here. was also reported in #273 #287

![Screenshot from 2021-08-02 19-43-46@3x](https://user-images.githubusercontent.com/91113/127904632-d6727b6e-ec4f-4c9e-8373-3b553dafa8f4.png)

when i set scaling to 1x and disabling mirroring, the experience is pretty bad. the UI glitches and wingpanel stays big over multiple displays... i have seen such behavior in the last years when i was still using elementary OS too. maybe this is the most unstable settings that can cause a huge mess. rebooting usually helps

![signal-2021-08-02-194830](https://user-images.githubusercontent.com/91113/127904709-13f4ee07-813e-48d6-a64a-9be4797e21cc.jpeg)

![signal-2021-08-02-195040](https://user-images.githubusercontent.com/91113/127904720-b260cb76-f56a-4be8-9f12-fce6921b1349.jpeg)

here is a video of the glitched UI: https://youtu.be/0ED7qzH3suU

the recording stopped because the disk was full, so that can also cause all kinds of issues

after the resolution is back to normal, the only issue is that the dock is tiny

![Screenshot from 2021-08-02 19-58-29](https://user-images.githubusercontent.com/91113/127905158-75f7f51e-ac64-4277-8927-2395a3e7250b.png)

**Comment by cassidyjames** [comment] 2021-08-12 17:58
This does sound like a duplicate of #273; correct me if I'm wrong, but I'd like to triage these reports together.

**Closed by cassidyjames** 2021-08-12 17:58 UTC
