### ISSUE TITLE
My System Setting's not change to dark mode

### ISSUE THREAD

**Issue by ardisujaya** [elementary/switchboard-plug-display#244] opened 2020-05-20 23:17 UTC
Why it don't change to dark mode? i already use Tweaks to change to dark mode
![Screenshot from 2020-05-21 07 14 57](https://user-images.githubusercontent.com/56907435/82506728-24b99180-9b33-11ea-8391-9fab2b6b5199.png)

**Comment by danrabbit** [comment] 2020-05-20 23:24
Tweaks is not supported. Closing as a duplicate of https://github.com/elementary/switchboard/issues/156

**Closed by danrabbit** 2020-05-20 23:24 UTC
