### ISSUE TITLE
Color profile setting

### ISSUE THREAD

**Issue by RandomnessRobin** [elementary/switchboard-plug-display#295] opened 2021-05-04 22:56 UTC
I've heard that there was a color profile choosing option in the past, and then it got removed. I wanted to know if that option can be added back. At the moment I'm having to install displaycal in order to choose my color profile. 

Really don't like installing third party apps to fix this. I mean elementary 6 is still in beta, so it's fine for now. Just wanted to add this request so that it can be seen.  Not sure if I can set color profiles via terminal. If there is I would like to know. Thanks in advance.

**Comment by danrabbit** [comment] 2021-05-04 23:45
This is a duplicate of #5

**Closed by danrabbit** 2021-05-04 23:45 UTC
Labels: Status: Duplicate
