### ISSUE TITLE
Color Manager

### ISSUE THREAD

**Issue by Ygor-Elinaldo** [elementary/switchboard-plug-display#381] opened 2024-03-03 20:23 UTC
### Problem

The issue at hand is related to color calibration/profile colors on the Elementary OS 8, where the default color profile for the monitor or another types of display appears to be incorrect, resulting in example: yellowish colors reminiscent of a perpetual light filter. The user expresses difficulty in finding a solution within the Elementary OS settings program and lacks the terminal expertise to fix this problem directly.

### Proposal

Introduce a dedicated color calibration option within the Elementary OS settings app to simplify the process of correcting color profiles. This option should provide an intuitive interface for users to select and apply the appropriate color profiles for their monitors and display.

### Prior Art (Optional)

Introduce a new 'colors' option in the Elementary OS settings app after the functionality found in the GNOME Control Center. GNOME Control Center features allow users to navigate to ‘Color’, select the problematic device, remove the existing profile, add a new color profile, and choose the desired color profile. This serves as a reference for creating an easy-to-use and effective solution in the Elementary OS environment.

**Comment by danirabbit** [comment] 2024-05-27 16:22
Thanks for your report! Closing as a duplicate of #5

**Closed by danirabbit** 2024-05-27 16:22 UTC
