### ISSUE TITLE
More scaling options

### ISSUE THREAD

**Issue by adelamare** [elementary/switchboard-plug-display#364] opened 2023-10-25 17:15 UTC
### Problem

When setting up my laptop I am finding that because my screen is 2160x1440. 

If I use a scaling factor of x2 it's way too big. If I use a scaling factor or one the screen is tiny and really hard to read. 

![Screenshot from laptop X2](https://github.com/elementary/switchboard-plug-display/assets/43961460/d39f3738-c1f3-4117-8998-89e66553f916)

![screenshot x1](https://github.com/elementary/switchboard-plug-display/assets/43961460/bc9d4fce-f640-4bfd-8df4-b91cf02199dc)

### Proposal

I propose that there is either a stepped gradient of .2 in magnification between X1 and X2 so you can cater for multiple screen sizes. 

### Prior Art (Optional)

Apple have a graded feature on MacOS.

**Comment by lenemter** [comment] 2024-01-08 07:26
Duplicate of https://github.com/elementary/switchboard-plug-display/issues/117

**Closed by lenemter** 2024-01-08 07:26 UTC
