### ISSUE TITLE
Please make an option to turn off screen rotation

### ISSUE THREAD

**Issue by bulbul0111** [elementary/switchboard-plug-display#230] opened 2020-03-20 16:08 UTC
My pc is HP-ProBook-430-G5, I have very annoying screen rotation while I am changing laptop position. Make a rotation lock button please in screen settings.
It an laptop, not tablet or smartphone, this button is very usefull.
If you will make this, your build will be just great!!!

Thank you very much!

**Comment by cassidyjames** [comment] 2020-07-08 17:23
Thanks for reporting this. It looks like it's a duplicate of #116.

**Closed by cassidyjames** 2020-07-08 17:23 UTC
