### ISSUE TITLE
settings window bigger than screen resolution

### ISSUE THREAD

**Issue by DanilChechkov** [elementary/switchboard-plug-display#251] opened 2020-07-22 08:00 UTC
G'day, guys! 
First of all, thank you for everything you do to make a great performance and awesome look of eOS, I really enjoy it!
Have no Idea where to write, so I decide to write here. A little problem - not a huge one:
My laptop screen resolution is 1366x768, and settings looks good and ok, take a look:
![Снимок экрана от 2020-07-22 10-49-02](https://user-images.githubusercontent.com/64303833/88149635-07737300-cc09-11ea-89c4-65439c0b6e8d.png)
But, after I install elementary tweaks I have an additional icon in settings window and the window become bigger than screen and there is nothing I can do
![Снимок экрана от 2020-07-22 10-53-02](https://user-images.githubusercontent.com/64303833/88150067-8e285000-cc09-11ea-8cc3-72e23fff88f6.png)
So the problem is - I even cannot change the size of a window - I can make it bigger, but cannot make it smaller, so it is hard to use some of the settings, for example I cannot click on the buttons that are in a down corners. Take a look - in the low part of a windows should be 4 buttons - i cannot even see them(that's information about system):
![Снимок экрана от 2020-07-22 10-58-44](https://user-images.githubusercontent.com/64303833/88150760-7d2c0e80-cc0a-11ea-8ba9-cb1772cdc7a1.png)

I am sure you have much more to do except this little problem, but it will be very nice of you if you solve it one day.

**Comment by NeroxHSE** [comment] 2020-08-04 16:06
I have the same issue, I think that the root of the problem is that there is no opportunity to change DPI correctly, there are many problems with resolution

**Comment by danrabbit** [comment] 2020-08-05 17:31
Closing as a duplicate of https://github.com/elementary/switchboard/issues/176

**Closed by danrabbit** 2020-08-05 17:31 UTC
