### ISSUE TITLE
Scaling Factor doesn't do anything

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-display#138] opened 2018-10-24 23:01 UTC
This appears to have broken sometime in the Juno cycle. I know there were a lot of Mutter changes, and I seem to recall the method for changing the scaling factor may have changed in GNOME Settings Daemon to accommodate Wayland.

**Comment by danrabbit** [comment] 2018-11-05 20:10
I can confirm this. It worked when it was merged, so that sucks

**Comment by danrabbit** [comment] 2018-11-05 20:13
I'm looking in dfeet and it looks like there's a `org.gnome.Mutter.DisplayConfig` and a `'legacy-ui-scaling-factor': 2` that seems interesting

**Comment by danrabbit** [comment] 2019-01-31 19:20
Should have been fixed in #146

**Closed by danrabbit** 2019-01-31 19:20 UTC
Labels: Priority: High, Status: Confirmed
