### ISSUE TITLE
Can't disable displays using the "Use this display" toggle

### ISSUE THREAD

**Issue by fnune** [elementary/switchboard-plug-display#274] opened 2020-11-27 17:04 UTC
## What Happened

I tried to disable one of my two monitors, and after applying the change, both displays are still active and the Wingpanel is very confused about where to go:

![screenshot-2020-11-27-18:02:31](https://user-images.githubusercontent.com/16181067/100471527-c15c7d80-30da-11eb-9588-cc0ee2b1029d.png)

## Expected Behavior

The disabled display no longer receives a signal.

## Steps to Reproduce

1. Use a two-monitor setup (in my case, a laptop plus an external monitor using USB-C)
2. Open the "Displays" widget and disable one of the displays
3. Observe how both displays are still active

## Platform Information

Elementary OS 5.1.7
Lenovo ThinkPad T15p with a 4K screen and an external 1440p Dell monitor via USB-C.

**Comment by davidmhewitt** [comment] 2021-08-18 12:23
I'm going to close this as a duplicate of #131

**Closed by davidmhewitt** 2021-08-18 12:23 UTC
