### ISSUE TITLE
All hell breaks loose after using low DPI and high DPI screens together

### ISSUE THREAD

**Issue by inad9300** [elementary/switchboard-plug-display#265] opened 2020-10-15 18:22 UTC
## Description
It is currently not possible to set different scaling factors for different displays. I assume this is already on your pipeline as a future feature, as should be providing scaling factors other than "Pixel Double". That aside, currently you have to compromise and use the same scaling factor for both screens. The related bug I'm experiencing is best described through the steps below.

### To Reproduce
1. Buy a laptop with high DPI and install elementary OS on it
2. Buy a screen with low DPI
3. Connect low DPI screen to high DPI laptop via DisplayPort
4. Set scaling factor to "LoDPI" so that you can fit more than one icon at the time in the external monitor (and prepare for needing a magnifying glass to see anything at all on the laptop)
5. Unplug said DisplayPort cable
6. See the laptop rendering everything out of place, specially in the multitasking view: icons of opened windows overlapping with one another, the squares representing your different desktops in weird positions...

## Platform information
- OS: elementary OS 5.1.7 Hera
- Device: Microsoft's Surface Pro 3

**Comment by nicekiwi** [comment] 2021-11-15 08:22
The same issue occurs in Odin with a High DPI Monitor and low DPI laptop screen. The OS seems unable to support a different scaling option only for one screen. I hope this will be solved soon.

**Comment by simjnd** [comment] 2022-01-19 07:14
Same problem here, I feel like it's a major issue productivity-wise

**Comment by lenemter** [comment] 2024-01-08 07:23
Duplicate of https://github.com/elementary/gala/issues/771

**Closed by lenemter** 2024-01-08 07:23 UTC
Labels: Status: Confirmed
