### ISSUE TITLE
Implementing dark theme doesn't save or change system wide

### ISSUE THREAD

**Issue by liamkinne** [elementary/switchboard-plug-display#115] opened 2018-09-07 15:07 UTC
I'm working on [this](https://www.bountysource.com/issues/7122508-set-color-profiles) bounty, and I've got something that almost works using this code:
```vala
Gtk.Settings.get_default().gtk_application_prefer_dark_theme = state;
```
And it does change to dark theme, but only for that window and it stops working after the switchboard is reopened.

Elementary Tweaks does this through editing the gtk-3.0 settings file directly, but that seems a bit hacky.

Is there a way to do this through the regular schemas? Since Code and Terminal already have 'prefer-dark-style' keys.

My fork and branch:
https://github.com/liamkinne/switchboard-plug-display/tree/prefer-dark-theme-switch

**Comment by danrabbit** [comment] 2018-09-07 15:13
Hey thanks for working on this issue! We're tracking it in GitHub here: https://github.com/elementary/switchboard-plug-display/issues/5

This issue is actually about managing display color profiles and ICC files, not about changing Gtk settings.

Closing this issue as a duplicate of #5

**Closed by danrabbit** 2018-09-07 15:13 UTC

**Comment by davidmhewitt** [comment] 2018-09-07 15:15
Hey,

I think you have misintepreted the issue. I think the color profiles that the issue refers to are more like color calibration of the monitor, rather than setting a systemwide dark theme. 

There is a separate plug/page in switchboard that allows you to color calibrate a display, so that the colors more accurately reflect real world colors or print colors, etc... This issue was refering to having that functionality built into the displays plug rather than having it in a separate page.

I don't think a PR to allow making the dark theme be used systemwide would be accepted for a couple of reasons:

- Not all apps are tested against or intended to be used with the dark theme. I don't think elementary will expect all 3rd party app developers to test their app against both the default and dark variants of the stylesheet.
- Only some apps having dark theme is intentional, allowing you to focus more on the contents of the window for more color critical work like photo editing.

**Comment by liamkinne** [comment] 2018-09-07 15:19
That makes a lot of sense... I thought it sounded a bit vague. No worries.
