### ISSUE TITLE
Can't turn off built-in display in my ntb

### ISSUE THREAD

**Issue by jprukner** [elementary/switchboard-plug-display#221] opened 2020-01-11 16:29 UTC
Hello! No matter what I do I am not able to turn off built-in display in my notebook. I've got Lenovo T400. Slider "Use this display" does nothing. I have to use xrandr to trun it off.

**Comment by immutable-pro** [comment] 2020-01-13 19:21
Hello! I am also having this issue. As a workaround, while a fix gets released, I am using "ARandR", which is a GUI for xrandr, just in case it helps.

**Comment by MarlonMrN** [comment] 2020-04-02 02:59
the main bug for this is https://github.com/elementary/switchboard-plug-display/issues/131
A pr is open and waiting review (for like a month now)

host + R    it's probably the best workaround, no additional sw is needed.

**Comment by davidmhewitt** [comment] 2020-08-10 12:10
Duplicate of #131

**Closed by davidmhewitt** 2020-08-10 12:10 UTC
Labels: Status: Duplicate
