### ISSUE TITLE
use mirror

### ISSUE THREAD

**Issue by Vaibhav22p-qw** [elementary/switchboard-plug-display#277] opened 2020-12-13 07:28 UTC

**Comment by meisenzahl** [comment] 2020-12-13 07:48
@Vaibhav22p-qw could you please add a description of your issue.

Please provide:

- What happended
- Expected Behavior
- Steps to Reproduce

Use the template for **Bug Report** when creating a new issue for reference.

**Comment by danrabbit** [comment] 2020-12-22 17:33
Since OP hasn't responded for over a week, closing as incomplete. Please feel free to reopen this issue with more information

**Closed by danrabbit** 2020-12-22 17:33 UTC
