### ISSUE TITLE
Display settings aren't being applied

### ISSUE THREAD

**Issue by h4ndshake** [elementary/switchboard-plug-display#106] opened 2018-07-07 00:19 UTC
Not sure if it's related (or the same) to #38 and it's a regression from Loki

Running Juno on an Optimus Enabled Laptop (with an GF106 GT630m). And i'm also on a "three monitor setup" (My broken laptop screen (which I disabled using the laptop Fn Key), my external monitor (probably isn't needed to give the model) on the VGA cable and the virtual nvidia screen.

Also using the nvidia-driver-390 package from AppCenter, with the Intel profile (Nvidia card can't draw anything on the screen..)

And the display settings (such as disabling the laptop screen and the nvidia virtual offscreen) doesn't do anything (not even blink the screens), worked fine on Loki.

How can I grab some logs from switchboard?

**Comment by naaando** [comment] 2018-09-22 17:03
I'm unable to disable monitors too

**Comment by cassidyjames** [comment] 2018-10-24 23:10
I know this was opened earlier, but since there is much more activity on #131 I'm going to mark this as a duplicate of it. Please feel free to follow along there and provide any more relevant information!

**Closed by cassidyjames** 2018-10-24 23:10 UTC
