### ISSUE TITLE
Nightshift dosen't work (AMD RX570)

### ISSUE THREAD

**Issue by Mierscheid** [elementary/switchboard-plug-display#278] opened 2020-12-18 22:02 UTC

**Comment by meisenzahl** [comment] 2020-12-19 06:29
Thank you for creating the issue. We are currently investigating how to determine if the running hardware supports Night Light. We have found that Night Light does not work on our builds for the Raspberry Pi and Pinebook Pro: https://github.com/elementary/onboarding/pull/118

Currently, on both devices, Night Light is available, but when it is active, the color temperature of the monitor does not change.

We assume that it is due to an unimplemented feature in the graphics driver.

So it would be very helpful if you could provide us with more info about your setup:

- version of elementary OS
- driver version

Please also provide:

- What happended
- Expected Behavior
- Steps to Reproduce

Use the template for **Bug Report** when creating a new issue for reference.

**Comment by danirabbit** [comment] 2023-06-08 17:21
Closing since this is probably a driver issue and we've had reports from others of hardware being supported in a newer kernel than what was shipped in 5.x

**Closed by danirabbit** 2023-06-08 17:21 UTC
