### ISSUE TITLE
Secondary display will not switch off (disable)

### ISSUE THREAD

**Issue by thelazygit** [elementary/switchboard-plug-display#249] opened 2020-06-28 19:03 UTC
Hi

The attached video shows the problem clearly, but in short, when I have two screens connected I am not able to disable the secondary screen. This is a problem as I share the secondary screen between my laptop on Display Port, and my desktop pc on VGA. What then happens is when it is switched to VGA, Elementary still opens panels on the secondary display. This lead me to believe there were more serious issues, until I switched the secondary screen to the laptop and saw that the apps I opened were all hiding there.

[Displays Issue 2020-06-28 13.57.04.mp4.zip](https://github.com/elementary/switchboard-plug-display/files/4842843/Displays.Issue.2020-06-28.13.57.04.mp4.zip)

**Comment by LongJohn-Silver** [comment] 2020-07-04 13:35
Same problem happens to me, in theory, you should go to Settings>Displays>Gear icon for display 02>Turn off by clicking on "Use This Display", but that doesn't do anything.

Just as a temporary solution, and if anyone that has the same problem is wondering how to "fix" this, this is what I do. Open a terminal, write <xrandr --listmonitors>, this should bring up a list with the monitors that you are using, find the one you want to disable (it will probably be something like "DP-1" or "HDMI-1") and then write <xrandr --output "NAMEOFTHEMONITORYOUWANTTOTURNOFF" --off>. When you want to turn it on, write <xrandr --auto>, go to Settings>Displays (now the second monitor will be on mirror mode, even if the settings says it isn't) click on mirror mode, save changes, unclick mirror mode, save changes. That's it, pretty annoying, I know.

OS: elementary OS 5.1.6 Hera x86_64 
Host: MS-7A15 1.0 
Kernel: 5.3.0-62-generic 
Shell: bash 4.4.20 
Resolution: 1440x900 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel Pentium G4560 (4) @ 3.500 
GPU: Intel HD Graphics 610 
Memory: 2411MiB / 7852MiB

**Comment by ohagiindiedev** [comment] 2020-07-30 23:51
me too, my external monitor just shuts down on command

**Comment by davidmhewitt** [comment] 2020-08-10 12:09
Duplicate of #131

**Closed by davidmhewitt** 2020-08-10 12:09 UTC
Labels: Status: Duplicate
