### ISSUE TITLE
Can't maximize and move freely windows on external display when it's positioned above the main

### ISSUE THREAD

**Issue by PanosWise** [elementary/switchboard-plug-display#61] opened 2017-08-01 18:02 UTC
Example:
![sc](https://user-images.githubusercontent.com/22100396/28839425-4f830f3a-76fc-11e7-8fac-9c3e340666fb.gif)
Please not this is how the windows behave there is nothing wrong with the .gif

My Display settings 
![screenshot from 2017-08-01 16 23 33](https://user-images.githubusercontent.com/22100396/28839104-3d3952ae-76fb-11e7-848c-7c38132a18fd.png)

**Comment by cassidyjames** [comment] 2017-08-01 18:36
Thanks for the issue and visualizations. This is actually a duplicate of https://github.com/elementary/gala/issues/7.

**Closed by cassidyjames** 2017-08-01 18:36 UTC
