### ISSUE TITLE
Night Light turn off at manual hour but is set to Sunrise to Sunset

### ISSUE THREAD

**Issue by RicaBenhossi** [elementary/switchboard-plug-display#240] opened 2020-04-27 09:10 UTC
I've seen that Night Light is on my computer has been off early than the sunrise and the hour it stops was the same time set on Manual configuration, 6:00 AM... 

As a test, I switched the option to MANUAL and set it from 6:00 PM to 6:10 AM. After that, I turned it back to Sunset to Sunrise. The next day, at 6:10 AM, Night Light got turned off. 

Seems that even if I set it to Sunset to Sunrise, it keep following the hours set on Manual configurations.

**Comment by danirabbit** [comment] 2023-06-08 17:22
Closing as a duplicate of #83

**Closed by danirabbit** 2023-06-08 17:22 UTC
