### ISSUE TITLE
Can't detect external display on MacBook Pro Late 2011

### ISSUE THREAD

**Issue by ImaCrea** [elementary/switchboard-plug-display#169] opened 2019-04-05 21:41 UTC
Hi dear contributors,
I'm running Elementary OS 5 Juno 64 bit on MacBook Pro Late 2011.

Its all working well and beautiful except one thing. I tried to plug a Firewire->DVI cable in order to watch a movie on a projector but it seems OS can't detect external display connected.

What can I do please?

Thanks for your dear help,

**Comment by ImaCrea** [comment] 2019-04-05 21:52
According to https://askubuntu.com/questions/1098340/external-monitor-not-working-with-macbook-pro-2011-and-defect-graphic-card it's looks like it's not possible to have it fixed :/ In any case, I let you see that message and decide to close or not this issue.

**Comment by peteruithoven** [comment] 2019-04-05 22:14
I'm afraid that even if there are options they are not at the display settings level so I'm closing this issue. 

Reading that topic the issue is that the integrated graphic card can't do it, but maybe you could look into using the Radeon graphic after installing the right driver?

> I've successfully installed Xubuntu 18.10 by disabling the Radeon graphic card via Grub and EFI partion.

> The integrated graphic card of these MacBooks seems not to be able to send images to an external display, i.e. there does not seem to be an software solution unfortunately (that means this question is actually not Ubuntu related). An USB to HDMI adapter (external graphic card) might be able to do the job and of course and a repair of the logic board too.

**Closed by peteruithoven** 2019-04-05 22:14 UTC

**Comment by ImaCrea** [comment] 2019-05-03 19:08
ok ;(
