### ISSUE TITLE
Show overlay when switching through Super + P 

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/switchboard-plug-display#185] opened 2019-08-31 13:38 UTC
I have a laptop + 1 monitor over HDMI.

When pressing windows key + p to switch through modes (laptop screen only, duplicated, extended to monitor, monitor only) I never know which mode will be the next that a press of super + p will go to. I want an overlay to indicate the current mode + the next mode while holding windows + p. The switching should only happen after releasing my hand from the key combination

**Comment by lenemter** [comment] 2024-01-08 07:15
Duplicate of https://github.com/elementary/gala/issues/109

**Closed by lenemter** 2024-01-08 07:15 UTC
